// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobC07AenFb_zatt265f_r2QTCPzhapmI',
    appId: '1:606665462074:web:33dda965c9086f219cc003',
    messagingSenderId: '606665462074',
    projectId: 'kant-81b00',
    authDomain: 'kant-81b00.firebaseapp.com',
    storageBucket: 'kant-81b00.firebasestorage.app',
    measurementId: 'G-ZSYBJS525W',
  );

  // 開発用のデフォルト設定（実際のFirebaseプロジェクトに置き換える必要があります）

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdf4JyLet75BkW_HoUom1MtSqYcPmlbrU',
    appId: '1:606665462074:android:2326b6fdb61f47669cc003',
    messagingSenderId: '606665462074',
    projectId: 'kant-81b00',
    storageBucket: 'kant-81b00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO1wUH2tkas8qsWU04sIK7XitPifdc5IQ',
    appId: '1:606665462074:ios:246df947377b8abc9cc003',
    messagingSenderId: '606665462074',
    projectId: 'kant-81b00',
    storageBucket: 'kant-81b00.firebasestorage.app',
    iosBundleId: 'com.example.taskKant1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO1wUH2tkas8qsWU04sIK7XitPifdc5IQ',
    appId: '1:606665462074:ios:246df947377b8abc9cc003',
    messagingSenderId: '606665462074',
    projectId: 'kant-81b00',
    storageBucket: 'kant-81b00.firebasestorage.app',
    iosBundleId: 'com.example.taskKant1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCobC07AenFb_zatt265f_r2QTCPzhapmI',
    appId: '1:606665462074:web:871a7fd8cb448e1b9cc003',
    messagingSenderId: '606665462074',
    projectId: 'kant-81b00',
    authDomain: 'kant-81b00.firebaseapp.com',
    storageBucket: 'kant-81b00.firebasestorage.app',
    measurementId: 'G-PSBHRQZT1Y',
  );

}