UPDATE public.knowledge AS k
SET construction = d.flag
FROM (
VALUES
('仮定法とは', '仮定法'::text, false),
('直説法と仮定法の比較', '仮定法'::text, false),
('仮定法の特徴：時制のずれ', '仮定法'::text, false),
('仮定法過去（現在の妄想）', '仮定法'::text, true),
('仮定法過去（未来の妄想）', '仮定法'::text, true),
('仮定法のbe動詞', '仮定法'::text, true),
('仮定法過去完了（過去の妄想）', '仮定法'::text, true),
('仮定法未来', '仮定法'::text, true),
('仮定法未来(1)were to', '仮定法'::text, true),
('仮定法未来(2)should', '仮定法'::text, true),
('未来の仮定法：were to と should の違い', '仮定法'::text, false),
('未来の仮定法：should の仮定法・主節の形', '仮定法'::text, true),
('仮定法：if の省略（倒置）', '仮定法'::text, true),
('If節のない仮定法：with / without / but for', '仮定法'::text, true),
('If節のない仮定法：ifの代用になるto不定詞（副詞用法）', '仮定法'::text, true),
('If節のない仮定法：ifの代用になるto不定詞（名詞用法）', '仮定法'::text, true),
('If節のない仮定法：otherwise', '仮定法'::text, true),
('If節のない仮定法：名詞 ＋ and ～', '仮定法'::text, true),
('If節のない仮定法：a 名詞 would ～', '仮定法'::text, true),
('If節のない仮定法：What would ～ do 型', '仮定法'::text, true),
('If節のない仮定法：主節のみのケース', '仮定法'::text, true),
('慣用表現：If I were you', '仮定法'::text, true),
('慣用表現：If it were not for', '仮定法'::text, true),
('慣用表現：If it had not been for', '仮定法'::text, true),
('慣用表現：It is time', '仮定法'::text, true),
('as if / as though', '仮定法'::text, true),
('混合仮定法', '仮定法'::text, true),
('will', '助動詞'::text, false),
('will(1)単純未来', '助動詞'::text, false),
('will(2)推量', '助動詞'::text, false),
('will(3)強い意思', '助動詞'::text, false),
('will(4)拒絶', '助動詞'::text, false),
('will(5)習性', '助動詞'::text, false),
('would', '助動詞'::text, false),
('would(2)固執・拒絶', '助動詞'::text, false),
('would(1)推量', '助動詞'::text, false),
('would(3)過去の習慣', '助動詞'::text, false),
('would(4)丁寧な依頼', '助動詞'::text, false),
('would(5)willの過去形（時制の一致）', '助動詞'::text, false),
('may', '助動詞'::text, false),
('might', '助動詞'::text, false),
('might+完了形', '助動詞'::text, false),
('must', '助動詞'::text, false),
('must(1)義務', '助動詞'::text, false),
('must(2)推定', '助動詞'::text, false),
('must not：禁止', '助動詞'::text, false),
('have to', '助動詞'::text, false),
('have to(1)義務', '助動詞'::text, false),
('have to(2)推量', '助動詞'::text, false),
('had to（過去形）', '助動詞'::text, false),
('will have to（未来形）', '助動詞'::text, false),
('don''t have to：する必要がない', '助動詞'::text, false),
('may①許可', '助動詞'::text, false),
('may②推量', '助動詞'::text, false),
('if節のない仮定法：I wish', '仮定法'::text, true)
) AS d(title_txt, unit_txt, flag)
WHERE k.subject_id = (SELECT id FROM public.subjects WHERE name = '英文法' LIMIT 1)
  AND k.content = d.title_txt
  AND (k.unit IS NOT DISTINCT FROM d.unit_txt);
